
export enum actionTypes {
    // nodeSelectingReducer:
    SWITCH_EDIT_MODE_TO_GIVEN_ID_ONLY = "SWITCH_EDIT_MODE_TO_GIVEN_ID_ONLY",
    TOGGLE_EDIT_MODE_FOR_GIVEN_ID = "TOGGLE_EDIT_MODE_FOR_GIVEN_ID",
    TOGGLE_HIGHLIGHT = "TOGGLE_HIGHLIGHT",

    // nodeListReducer:
    CREATE_NODE = "CREATE_NODE",
    UPDATE_NODE_CONTENT = "UPDATE_NODE_CONTENT",
    DELETE_NODE_WITH_GIVEN_ID = "DELETE_NODE_WITH_GIVEN_ID",
    ADD_NODE_FROM_MEMORY = "ADD_NODE_FROM_MEMORY",
    MOVE_CLOSER_TO_ANCESTOR = "MOVE_CLOSER_TO_ANCESTOR",
}